import random

"""
this is the v0 MVP for a workout generator
by Chaira Harder

workout generated by:
- level of comfort doing certain activities (specified) 
- athletic goals (aesthetic, athleticism skill, other skill like calesthetics, flexibility, etc.)

how this differs from other workout generators like
https://musclewiki.com/workout-generator/generated-workout/

- takes into account the specific exercises you enjoy or feel comfortable doing
- take your personal goals into account more specifically than just (lose weight, gain strengh, gain muscle)
- more strategic workout than just being "randomly" thrown together -- backed by research... at least somewhat. moreso later on in developed versions.
- cuter. gen z.

*elevator pitch at conway. december.

"""

def start_clear():
    print('----------------------------------------\n|/////////////////////////////////|\n----------------------------------------\n\twerkeut!')

def get_user_background():
    workout_type = input('select workout type (athletic, aesthetic, weight-loss, ):\n')
    

    print(workout_type)

    # this will need to be changed to be a datatype that saves...other info -- fix later
    background = workout_type

    return background

def gen_workout():
    background = get_user_background()




def main():
    start_clear()
    gen_workout()